spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/frotaconf
spring.datasource.username=postgres
spring.datasource.password=28072006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security default user for Basic Auth
spring.security.user.name=admin
spring.security.user.password=admin
